#**Assignment**

## This is the assignment in week 9 ML TOOLBOX - Numpy

## Consider the below code to answer further questions:
##import numpy as np
## list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
## array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans- Yes there is a difference in data type variable list and array_list
variable list is a list data type and array_list is a array data type


In [19]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [20]:
for i in list_:
  print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [22]:
for i in array_list:
  print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
## array_list = np.array(object = list_, dtype = int)

In [27]:
 array_list = np.array(object = list_, dtype = int)

In [28]:
array_list

array([1, 2, 3, 4, 5])

In [30]:
print("Data type of elements in 'list_':")
for item in list_:
    print(type(item))

print("\nData type of elements in 'array_list':")
for item in array_list:
    print(type(item))

Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Yes there will be change but only in array_list becouse we have done changes only in array_list variable so the datatype of all the element become int type and data type of list_ remain same

In [32]:
# Consider the below code to answer further questions:

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [33]:
np.shape(num_array)

(2, 3)

In [34]:
np.size(num_array)

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [37]:
array = np.zeros((3,3))

In [38]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])